# Generated by Django 4.2.3 on 2023-07-23 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=22, null=True)),
                ('uid', models.CharField(max_length=77, null=True)),
                ('email', models.CharField(max_length=22, null=True)),
                ('password', models.CharField(max_length=22, null=True)),
                ('lang', models.CharField(max_length=11, null=True)),
            ],
            options={
                'db_table': 'person',
                'indexes': [models.Index(fields=['email', 'uid'], name='person_email_39d62a_idx')],
            },
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.CharField(max_length=22, null=True)),
                ('region', models.CharField(max_length=22, null=True)),
                ('city', models.CharField(max_length=22, null=True)),
                ('zipcode', models.CharField(max_length=22, null=True)),
                ('lat', models.DecimalField(decimal_places=11, max_digits=13, null=True)),
                ('lng', models.DecimalField(decimal_places=11, max_digits=13, null=True)),
            ],
            options={
                'db_table': 'location',
                'indexes': [models.Index(fields=['zipcode'], name='location_zipcode_da8348_idx')],
            },
        ),
        migrations.CreateModel(
            name='LastVisit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField(null=True)),
                ('time', models.DateTimeField()),
            ],
            options={
                'db_table': 'lastvisit',
                'indexes': [models.Index(fields=['user_id'], name='lastvisit_user_id_72bf74_idx')],
            },
        ),
        migrations.CreateModel(
            name='CollectionLines',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField(null=True)),
                ('colection_id', models.IntegerField(null=True)),
                ('order_id', models.IntegerField(null=True)),
                ('client_name', models.IntegerField(null=True)),
                ('delivery_date', models.CharField(max_length=33)),
                ('palets', models.IntegerField(null=True)),
                ('kilos', models.IntegerField(null=True)),
                ('export', models.CharField(max_length=11)),
                ('week', models.IntegerField(null=True)),
                ('country', models.CharField(max_length=22)),
                ('region', models.CharField(max_length=22)),
                ('city', models.CharField(max_length=22)),
                ('lat', models.DecimalField(decimal_places=11, max_digits=13, null=True)),
                ('lng', models.DecimalField(decimal_places=11, max_digits=13, null=True)),
                ('truck', models.IntegerField(null=True)),
                ('truck_name', models.CharField(max_length=22)),
                ('order', models.IntegerField(null=True)),
                ('meters', models.IntegerField(null=True)),
                ('zipcode', models.CharField(max_length=22, null=True)),
                ('conductor_id', models.IntegerField(null=True)),
            ],
            options={
                'db_table': 'colectionlines',
                'indexes': [models.Index(fields=['colection_id', 'user_id'], name='colectionli_colecti_313d49_idx')],
            },
        ),
        migrations.CreateModel(
            name='Collection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField(null=True)),
                ('date', models.CharField(max_length=22)),
                ('week', models.IntegerField(null=True)),
                ('pallets', models.IntegerField(null=True)),
                ('kilos', models.IntegerField(null=True)),
            ],
            options={
                'db_table': 'colection',
                'indexes': [models.Index(fields=['user_id'], name='colection_user_id_697873_idx')],
            },
        ),
    ]
