# Generated by Django 4.2.3 on 2023-07-25 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_alter_lastvisit_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='collection',
            name='uid',
            field=models.CharField(max_length=33, null=True),
        ),
    ]
