# Generated by Django 4.2.3 on 2023-07-25 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_collection_uid'),
    ]

    operations = [
        migrations.AddField(
            model_name='collection',
            name='file_name',
            field=models.CharField(max_length=22, null=True),
        ),
    ]
