# Generated by Django 4.2.3 on 2023-07-25 08:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_collection_file_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='collection',
            name='week',
        ),
        migrations.RemoveField(
            model_name='collectionlines',
            name='week',
        ),
    ]
