# Generated by Django 4.2.3 on 2023-07-25 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_remove_collection_week_remove_collectionlines_week'),
    ]

    operations = [
        migrations.AddField(
            model_name='collection',
            name='week',
            field=models.IntegerField(null=True),
        ),
    ]
