# Generated by Django 4.2.3 on 2023-07-25 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_collection_week'),
    ]

    operations = [
        migrations.AddField(
            model_name='lastvisit',
            name='visit',
            field=models.IntegerField(null=True),
        ),
    ]
