# Generated by Django 4.2.3 on 2023-07-26 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0009_lastvisit_visit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collectionlines',
            name='client_name',
            field=models.CharField(max_length=33, null=True),
        ),
    ]
