# Generated by Django 4.2.3 on 2023-07-26 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0010_alter_collectionlines_client_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collectionlines',
            name='lat',
            field=models.CharField(max_length=33, null=True),
        ),
        migrations.AlterField(
            model_name='collectionlines',
            name='lng',
            field=models.CharField(max_length=33, null=True),
        ),
    ]
