# Generated by Django 4.2.3 on 2023-07-28 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0011_alter_collectionlines_lat_alter_collectionlines_lng'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='city',
            field=models.CharField(max_length=22, null=True),
        ),
        migrations.AddField(
            model_name='person',
            name='country',
            field=models.CharField(max_length=22, null=True),
        ),
        migrations.AddField(
            model_name='person',
            name='region',
            field=models.CharField(max_length=22, null=True),
        ),
    ]
