# Generated by Django 4.2.3 on 2023-07-28 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0012_person_city_person_country_person_region'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='lat',
            field=models.CharField(max_length=33, null=True),
        ),
        migrations.AddField(
            model_name='person',
            name='lng',
            field=models.CharField(max_length=33, null=True),
        ),
    ]
