# Generated by Django 4.2.3 on 2023-07-29 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0013_person_lat_person_lng'),
    ]

    operations = [
        migrations.AddField(
            model_name='collectionlines',
            name='line_id',
            field=models.IntegerField(null=True),
        ),
    ]
