# Generated by Django 4.2.3 on 2023-07-29 23:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0014_collectionlines_line_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collection',
            name='date',
            field=models.CharField(max_length=22, null=True),
        ),
        migrations.AlterField(
            model_name='collectionlines',
            name='city',
            field=models.CharField(max_length=22, null=True),
        ),
        migrations.AlterField(
            model_name='collectionlines',
            name='country',
            field=models.CharField(max_length=22, null=True),
        ),
        migrations.AlterField(
            model_name='collectionlines',
            name='export',
            field=models.CharField(max_length=11, null=True),
        ),
        migrations.AlterField(
            model_name='collectionlines',
            name='region',
            field=models.CharField(max_length=22, null=True),
        ),
        migrations.AlterField(
            model_name='collectionlines',
            name='truck_name',
            field=models.CharField(max_length=22, null=True),
        ),
    ]
