# Generated by Django 4.2.3 on 2023-07-29 23:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0015_alter_collection_date_alter_collectionlines_city_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collectionlines',
            name='truck_name',
            field=models.CharField(max_length=33, null=True),
        ),
    ]
